### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by knightking10** [clanner/simcitybuildit#1]
why does this only have Readme.md?

**Comment by clanner** [comment]
so you did not read the readme then?
work in progress.

**Comment by knightking10** [comment]
what can i do with this project?

**Comment by BerkanYildiz** [comment]
Knight, it's a SimCity Documation.. (facepalm)

**Comment by knightking10** [comment]
ik you should't use skype emoji there

**Comment by BerkanYildiz** [comment]
@knightking10 I do what i want :) (rofl)
